### ISSUE TITLE
Warnings when compiling

### ISSUE THREAD

**Issue by gusmccallum** [joshuali7536/LennahSSG#2]
My compiler flagged some warnings regarding multiple declarations as well as declaring functions "extern" and then later "static" .

![image](https://user-images.githubusercontent.com/61558904/133714024-de9ff555-ea2d-46a4-b5e2-6766bd6a371f.png)

Compiled and ran fine after ignoring the warnings though!

**Comment by joshuali7536** [comment]
Updated functions to have static.
