### ISSUE TITLE
Don't put build artifacts in git

### ISSUE THREAD

**Issue by humphd** [joshuali7536/LennahSSG#5]
You want to avoid putting binaries or generated files into git, and instead focus on source code.  It looks like you've added your entire VS solution and all generated/built files and folders.  You can add a [.gitignore for VS](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore) to deal with this, and use `git rm -fr filenames...` to remove these.

**Comment by joshuali7536** [comment]
updated the .gitignore file to deal with the binary files.
