### ISSUE TITLE
Markdown Support

### ISSUE THREAD

**Issue by gusmccallum** [joshuali7536/LennahSSG#8]
I'd like to add markdown support to your SSG by: 

1. Checking around line 50 for a ".md" filetype
2. Adding logic in your readTxt() function to find the first and last instance of a string such as `"*"` / 
`"_"` or `"**"` / `"__"` and prepend/append the relevant html tags to the line for italics and bold, respectively

**Comment by joshuali7536** [comment]
Markdown Support Added
